name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Install TypeScript
        run: npm install --save-dev typescript

      - name: Modify script.ts for production
        run: |
          sed -i "s|let __ENV__ = 'development';|let __ENV__ = 'prod';|g" script.ts
          sed -i "s|const templateDir = '/templates/';|const templateDir = '/resumegick/templates/';|g" script.ts

      - name: Compile TypeScript
        run: npx tsc

      - name: Compile Sass
        run: npx sass styles:styles

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: . # Upload the entire repository

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2